# first line starts with ‘FROM’ defines the base image or operating system to start the build process
FROM ubuntu

# full name and email address of author or image creator
MAINTAINER maze ndukum ndukummaze@wustl.edu

# command to be executed to build the image
RUN apt-get update

# specific command to be executed within the container
CMD ["echo", "hello world...! from my first docker image"]

